version: '3'

services:
  node:
    build: ./docker/node
    image: node
    container_name: node
    volumes:
      - ./:/usr/src/app
    #command: sh -c "cd next-app && npm run dev" #nextを使う時
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    
  python3:
    build: ./docker/python3
    image: python3
    container_name: python3
    volumes:
      - ./docker/python3/src:/src
    tty: true
    stdin_open: true