version: '3'

services:
  go:
    build: ./docker/go.dockerfile
    image: go
    container_name: go
    tty: true
    stdin_open: true
    volumes:
      - ./src/:/go/src
    ports:
      - 8080:8080