version: '3'

services:
  mysql:
    build:
      context: ./docker
      dockerfile: mysql.dockerfile
    image: mysql
    container_name: mysql
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      #- MYSQL_USER=
      #- MYSQL_PASSWORD=
    ports:
      - 3306:3306
volumes:
  db-store: